CREATE TABLE CONTACT_TABLE1(
ID INT PRIMARY KEY NOT NULL,
EMAIL VARCHAR(100) NOT NULL,
FNAME VARCHAR(100) NOT NULL,
INAME VARCHAR(100) NOT NULL,
COMPANY VARCHAR(100) NOT NULL,
ACTIVE_FLAG INT NOT NULL,
OPT_OUT INT NOT NULL
);

INSERT INTO CONTACT_TABLE1 VALUES (123,'a@a.com','Kian','Seth','ABC',1,1),
(133,'b@a.com','Neha','Seth','ABC',1,0),
(234,'c@c.com','Puru','Malik','CDF',0,0),
(342,'d@d.com','Sid','Maan','TEG',1,0);

select* from CONTACT_TABLE1;

SELECT ID,EMAIL,FNAME,INAME,COMPANY,ACTIVE_FLAG,OPT_OUT FROM CONTACT_TABLE1 WHERE ACTIVE_FLAG = 1;

DELETE FROM CONTACT_TABLE1 WHERE OPT_OUT=1;

DELETE FROM CONTACT_TABLE1 WHERE COMPANY ='ABC';
DELETE FROM CONTACT_TABLE1 WHERE EMAIL='MILI';

INSERT INTO CONTACT_TABLE1 VALUES(658,'mili@gmail.com','MILI','','DGH',1,1);
select distinct ID,EMAIL,FNAME,INAME,COMPANY,ACTIVE_FLAG,OPT_OUT from CONTACT_TABLE1;
UPDATE CONTACT_TABLE1 SET FNAME = 'NITI' WHERE FNAME='MILI';

